openapi: 3.0.0
info:
  license:
    name: MIT
  title: AlsoRAN Connection API
  version: 1.0.0
servers:
- url: http://localhost/v1
paths:
  /addConnection:
    post:
      operationId: addConnection
      requestBody:
        content:
          application/json:
            examples:
              example1:
                value:
                  operationType: setupNg
                  ipAddress: 12.13.14.15
            schema:
              $ref: '#/components/schemas/ConnectionInfo'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RevisionNumber'
          description: Success
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Failure
      summary: Instructs a worker to add a connection
components:
  schemas:
    ConnectionInfo:
      example:
        ipAddress: ipAddress
        operationType: null
      properties:
        operationType:
          $ref: '#/components/schemas/OperationType'
        ipAddress:
          type: string
      required:
      - ipAddress
      - operationType
      type: object
    OperationType:
      enum:
      - setupNg
      - joinNg
      - addF1
      - addE1
      type: string
    RevisionNumber:
      description: Revision number of the worker refresh just sent by this worker
      type: integer
    Error:
      type: string

