openapi: "3.0.0"
info:
  version: 1.0.0
  title: AlsoRAN Node Control API
  license:
    name: MIT
servers:
  - url: http://localhost/v1
paths:
  /worker:
    post:
      summary: Refresh worker request
      operationId: refreshWorker
      requestBody:
        description: Worker information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshWorkerReq'
      responses:
        '200':
          description: Refresh worker response
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/RefreshWorkerRsp"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      callbacks:
        interfaceManagement:
          # This path is chosen to work around a bug in the Rust OpenAPI generator.  The
          # callback client API requires a full URL as input.  The server API is passed just the path
          # after the http://.../v1.  This construction lets us satisfy both of these inconsistent alternatives.
          # The essence of this workaround is that the first element of the callback path must be a parameter.
          '{$request.body#/callbackUrl}':
            post: 
              summary: A worker is instructed to trigger an interface management procedure on the given TNLA.
              description: | 
                The worker must carry out the given procedure on the given TNLA.  If the procedure succeeds then  
                the worker should send a successful response to this call.  If the procedure fails then the
                worker should send an unsuccessful response to this call.
              operationId: triggerInterfaceManagement
              requestBody: 
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/InterfaceManagementReq'
              responses:
                '204':
                  description: Interface management response
                default:
                  description: Unexpected error
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Error"
components:
  schemas:
    RefreshWorkerReq:
      type: object
      required:
        - workerUniqueId
        - callbackUrl
        - f1Address
        - connectedAmfs
        - connectedDus
      properties:
        workerUniqueId:
          type: string
          format: uuid
        callbackUrl:
          type: string
          format: url
        f1Address:
          $ref: '#/components/schemas/TransportAddress'
        connectedAmfs:
          type: array
          items: 
            type: string
        connectedDus:
          type: array
          items: 
            type: string
    RefreshWorkerRsp:
      type: object
      required: 
        - amfAddresses
      properties:
        amfAddresses:
          type: array
          items: 
            $ref: '#/components/schemas/TransportAddress'
          minItems: 1
          uniqueItems: true
    InterfaceManagementReq:
      type: object
      required: 
        - procedure
      properties:
        procedure: 
          type: string
          enum: 
            - ngsetup
            - ranconfigurationupdate
    TransportAddress:
      type: object
      required: 
        - host
      properties:
        host:
          type: string
          format: hostname
        port: 
          type: integer
          minimum: 1
          maximum: 65535
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string