openapi: 3.0.0
info:
  license:
    name: MIT
  title: AlsoRAN Node Control API
  version: 1.0.0
servers:
- url: http://localhost/v1
paths:
  /worker:
    post:
      callbacks:
        interfaceManagement:
          '{$request.body#/callbackUrl}':
            post:
              description: "The worker must carry out the given procedure on the given\
                \ TNLA.  If the procedure succeeds then  \nthe worker should send\
                \ a successful response to this call.  If the procedure fails then\
                \ the\nworker should send an unsuccessful response to this call.\n"
              operationId: triggerInterfaceManagement
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/InterfaceManagementReq'
                required: true
              responses:
                "204":
                  description: Interface management response
                default:
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Error'
                  description: Unexpected error
              summary: A worker is instructed to trigger an interface management procedure
                on the given TNLA.
              x-callback-request: true
      operationId: refreshWorker
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshWorkerReq'
        description: Worker information
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshWorkerRsp'
          description: Refresh worker response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Refresh worker request
components:
  schemas:
    RefreshWorkerReq:
      example:
        workerUniqueId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        connectedAmfs:
        - connectedAmfs
        - connectedAmfs
        f1Address:
          port: 5249
          host: host
        callbackUrl: http://example.com/aeiou
        connectedDus:
        - connectedDus
        - connectedDus
      properties:
        workerUniqueId:
          format: uuid
          type: string
        callbackUrl:
          format: url
          type: string
        f1Address:
          $ref: '#/components/schemas/TransportAddress'
        connectedAmfs:
          items:
            type: string
          type: array
        connectedDus:
          items:
            type: string
          type: array
      required:
      - callbackUrl
      - connectedAmfs
      - connectedDus
      - f1Address
      - workerUniqueId
      type: object
    RefreshWorkerRsp:
      example:
        amfAddresses:
        - port: 5249
          host: host
        - port: 5249
          host: host
      properties:
        amfAddresses:
          items:
            $ref: '#/components/schemas/TransportAddress'
          minItems: 1
          type: array
          uniqueItems: true
      required:
      - amfAddresses
      type: object
    InterfaceManagementReq:
      example:
        procedure: ngsetup
      properties:
        procedure:
          enum:
          - ngsetup
          - ranconfigurationupdate
          type: string
      required:
      - procedure
      type: object
    TransportAddress:
      example:
        port: 5249
        host: host
      properties:
        host:
          format: hostname
          type: string
        port:
          maximum: 65535
          minimum: 1
          type: integer
      required:
      - host
      type: object
    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object

