// Copyright (c) Nicholas Larkin
// Autogenerated from NGAP-CommonDataTypes.asn
use bitvec::prelude::*;
pub type BitString = BitVec<u8, Msb0>;

// Criticality
#[derive(Clone, Copy)]
pub enum Criticality {
    Reject,
    Ignore,
    Notify,
}

// Presence
#[derive(Clone, Copy)]
pub enum Presence {
    Optional,
    Conditional,
    Mandatory,
}

// PrivateIeId
#[derive(Clone)]
pub enum PrivateIeId {
    Local(u16),
    Global(Vec<u8>),
}

// ProcedureCode
#[derive(Clone)]
pub struct ProcedureCode(pub u8);

// ProtocolExtensionId
#[derive(Clone)]
pub struct ProtocolExtensionId(pub u16);

// ProtocolIeId
#[derive(Clone)]
pub struct ProtocolIeId(pub u16);

// TriggeringMessage
#[derive(Clone, Copy)]
pub enum TriggeringMessage {
    InitiatingMessage,
    SuccessfulOutcome,
    UnsuccessfullOutcome,
}
