// Copyright (c) Nicholas Larkin
// Autogenerated from NGAP-PDU-Contents.asn

use asn1::BitString;
use asn1::aper::{
    APerElement, Constraint, Constraints, DecodeError, Decoder, EncodeError, Encoding,
    UNCONSTRAINED,
};
use num_derive::FromPrimitive;
use num_traits::FromPrimitive;use super::ies::*;

