[workspace]

members = [
    "common",
    "sctp",
    "net",
    "mocks",
    "ngap",
    "f1ap",
    "e1ap",
    "rrc",
    "pdcp",
    "node-control-api",
    "gnbcu",
    "coordinator",
    "gnbdu-sim",
    "integration-tests"
]