[workspace]

members = [
    "asn1-per",
    "common",
    "sctp",
    "net",
    "mocks",
    "ngap",
    "f1ap",
    "e1ap",
    "rrc",
    "pdcp",
    "gnb-cu-cp",
    "connection-api",
    "coordination-api",
    "gnb-cu-cp-coordinator",
    "gnb-du-sim",
    "integration-tests"
]