[workspace]

members = [
    "gnbcu-scaling-prototype/worker",
    "gnbcu-scaling-prototype/node-control-api",
    "gnbcu-scaling-prototype/coordinator",
    "common",
    "integration-tests",
    "sctp",
    "net",
    "ngap",
    "f1ap",
    "gnbcu"
]