[workspace]

members = [
    "worker",
    "node-control-api",
    "coordinator",
    "common",
    "integration-tests",
    "also-sctp",
    "also-net",
    "pdu-convert-derive",
    "asn1-generator/src/ngap",
    "asn1-generator/src/f1ap"
]