// Copyright (c) Nicholas Larkin
// Autogenerated from F1AP-IEs.asn
use super::common::*;

use asn1::BitString;
use asn1::aper::{
    APerElement, Constraint, Constraints, DecodeError, Decoder, EncodeError, Encoding,
    UNCONSTRAINED,
};
use num_derive::FromPrimitive;
use num_traits::FromPrimitive;
