// Copyright (c) Nicholas Larkin
// Autogenerated from F1AP-PDU-Contents.asn

use super::common::*;
use super::ies::*;

// Reset
#[derive(Clone)]
pub struct Reset {
    pub transaction_id: TransactionId,
    pub cause: Cause,
    pub reset_type: ResetType,
}

// ResetType
#[derive(Clone)]
pub enum ResetType {
    F1Interface(ResetAll),
    PartOfF1Interface(UeAssociatedLogicalF1ConnectionListRes),
}

// ResetAll
#[derive(Clone, Copy)]
pub enum ResetAll {
    ResetAll,
}

// UeAssociatedLogicalF1ConnectionListRes
#[derive(Clone)]
pub struct UeAssociatedLogicalF1ConnectionListRes(pub Vec<UeAssociatedLogicalF1ConnectionItemRes>);

// ResetAcknowledge
#[derive(Clone)]
pub struct ResetAcknowledge {
    pub transaction_id: TransactionId,
    pub ue_associated_logical_f1_connection_list_res_ack:
        Option<UeAssociatedLogicalF1ConnectionListResAck>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// UeAssociatedLogicalF1ConnectionListResAck
#[derive(Clone)]
pub struct UeAssociatedLogicalF1ConnectionListResAck(
    pub Vec<UeAssociatedLogicalF1ConnectionItemResAck>,
);

// ErrorIndication
#[derive(Clone)]
pub struct ErrorIndication {
    pub transaction_id: TransactionId,
    pub gnb_cu_ue_f1ap_id: Option<GnbCuUeF1apId>,
    pub gnb_du_ue_f1ap_id: Option<GnbDuUeF1apId>,
    pub cause: Option<Cause>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// F1SetupRequest
#[derive(Clone)]
pub struct F1SetupRequest {
    pub transaction_id: TransactionId,
    pub gnb_du_id: GnbDuId,
    pub gnb_du_name: Option<GnbDuName>,
    pub gnb_du_served_cells_list: Option<GnbDuServedCellsList>,
    pub gnb_du_rrc_version: RrcVersion,
    pub transport_layer_address_info: Option<TransportLayerAddressInfo>,
    pub bap_address: Option<BapAddress>,
    pub extended_gnb_cu_name: Option<ExtendedGnbCuName>,
}

// GnbDuServedCellsList
#[derive(Clone)]
pub struct GnbDuServedCellsList(pub Vec<GnbDuServedCellsItem>);

// F1SetupResponse
#[derive(Clone)]
pub struct F1SetupResponse {
    pub transaction_id: TransactionId,
    pub gnb_cu_name: Option<GnbCuName>,
    pub cells_to_be_activated_list: Option<CellsToBeActivatedList>,
    pub gnb_cu_rrc_version: RrcVersion,
    pub transport_layer_address_info: Option<TransportLayerAddressInfo>,
    pub ul_bh_non_up_traffic_mapping: Option<UlBhNonUpTrafficMapping>,
    pub bap_address: Option<BapAddress>,
    pub extended_gnb_du_name: Option<ExtendedGnbDuName>,
}

// CellsToBeActivatedList
#[derive(Clone)]
pub struct CellsToBeActivatedList(pub Vec<CellsToBeActivatedListItem>);

// F1SetupFailure
#[derive(Clone)]
pub struct F1SetupFailure {
    pub transaction_id: TransactionId,
    pub cause: Cause,
    pub time_to_wait: Option<TimeToWait>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// GnbDuConfigurationUpdate
#[derive(Clone)]
pub struct GnbDuConfigurationUpdate {
    pub transaction_id: TransactionId,
    pub served_cells_to_add_list: Option<ServedCellsToAddList>,
    pub served_cells_to_modify_list: Option<ServedCellsToModifyList>,
    pub served_cells_to_delete_list: Option<ServedCellsToDeleteList>,
    pub cells_status_list: Option<CellsStatusList>,
    pub dedicated_si_delivery_needed_ue_list: Option<DedicatedSiDeliveryNeededUeList>,
    pub gnb_du_id: Option<GnbDuId>,
    pub gnb_du_tnl_association_to_remove_list: Option<GnbDuTnlAssociationToRemoveList>,
    pub transport_layer_address_info: Option<TransportLayerAddressInfo>,
}

// ServedCellsToAddList
#[derive(Clone)]
pub struct ServedCellsToAddList(pub Vec<ServedCellsToAddItem>);

// ServedCellsToModifyList
#[derive(Clone)]
pub struct ServedCellsToModifyList(pub Vec<ServedCellsToModifyItem>);

// ServedCellsToDeleteList
#[derive(Clone)]
pub struct ServedCellsToDeleteList(pub Vec<ServedCellsToDeleteItem>);

// CellsStatusList
#[derive(Clone)]
pub struct CellsStatusList(pub Vec<CellsStatusItem>);

// DedicatedSiDeliveryNeededUeList
#[derive(Clone)]
pub struct DedicatedSiDeliveryNeededUeList(pub Vec<DedicatedSiDeliveryNeededUeItem>);

// GnbDuTnlAssociationToRemoveList
#[derive(Clone)]
pub struct GnbDuTnlAssociationToRemoveList(pub Vec<GnbDuTnlAssociationToRemoveItem>);

// GnbDuConfigurationUpdateAcknowledge
#[derive(Clone)]
pub struct GnbDuConfigurationUpdateAcknowledge {
    pub transaction_id: TransactionId,
    pub cells_to_be_activated_list: Option<CellsToBeActivatedList>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
    pub cells_to_be_deactivated_list: Option<CellsToBeDeactivatedList>,
    pub transport_layer_address_info: Option<TransportLayerAddressInfo>,
    pub ul_bh_non_up_traffic_mapping: Option<UlBhNonUpTrafficMapping>,
    pub bap_address: Option<BapAddress>,
}

// GnbDuConfigurationUpdateFailure
#[derive(Clone)]
pub struct GnbDuConfigurationUpdateFailure {
    pub transaction_id: TransactionId,
    pub cause: Cause,
    pub time_to_wait: Option<TimeToWait>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// GnbCuConfigurationUpdate
#[derive(Clone)]
pub struct GnbCuConfigurationUpdate {
    pub transaction_id: TransactionId,
    pub cells_to_be_activated_list: Option<CellsToBeActivatedList>,
    pub cells_to_be_deactivated_list: Option<CellsToBeDeactivatedList>,
    pub gnb_cu_tnl_association_to_add_list: Option<GnbCuTnlAssociationToAddList>,
    pub gnb_cu_tnl_association_to_remove_list: Option<GnbCuTnlAssociationToRemoveList>,
    pub gnb_cu_tnl_association_to_update_list: Option<GnbCuTnlAssociationToUpdateList>,
    pub cells_to_be_barred_list: Option<CellsToBeBarredList>,
    pub protected_eutra_resources_list: Option<ProtectedEutraResourcesList>,
    pub neighbour_cell_information_list: Option<NeighbourCellInformationList>,
    pub transport_layer_address_info: Option<TransportLayerAddressInfo>,
    pub ul_bh_non_up_traffic_mapping: Option<UlBhNonUpTrafficMapping>,
    pub bap_address: Option<BapAddress>,
}

// CellsToBeDeactivatedList
#[derive(Clone)]
pub struct CellsToBeDeactivatedList(pub Vec<CellsToBeDeactivatedListItem>);

// GnbCuTnlAssociationToAddList
#[derive(Clone)]
pub struct GnbCuTnlAssociationToAddList(pub Vec<GnbCuTnlAssociationToAddItem>);

// GnbCuTnlAssociationToRemoveList
#[derive(Clone)]
pub struct GnbCuTnlAssociationToRemoveList(pub Vec<GnbCuTnlAssociationToRemoveItem>);

// GnbCuTnlAssociationToUpdateList
#[derive(Clone)]
pub struct GnbCuTnlAssociationToUpdateList(pub Vec<GnbCuTnlAssociationToUpdateItem>);

// CellsToBeBarredList
#[derive(Clone)]
pub struct CellsToBeBarredList(pub Vec<CellsToBeBarredItem>);

// ProtectedEutraResourcesList
#[derive(Clone)]
pub struct ProtectedEutraResourcesList(pub Vec<ProtectedEutraResourcesItem>);

// NeighbourCellInformationList
#[derive(Clone)]
pub struct NeighbourCellInformationList(pub Vec<NeighbourCellInformationItem>);

// GnbCuConfigurationUpdateAcknowledge
#[derive(Clone)]
pub struct GnbCuConfigurationUpdateAcknowledge {
    pub transaction_id: TransactionId,
    pub cells_failed_to_be_activated_list: Option<CellsFailedToBeActivatedList>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
    pub gnb_cu_tnl_association_setup_list: Option<GnbCuTnlAssociationSetupList>,
    pub gnb_cu_tnl_association_failed_to_setup_list: Option<GnbCuTnlAssociationFailedToSetupList>,
    pub dedicated_si_delivery_needed_ue_list: Option<DedicatedSiDeliveryNeededUeList>,
    pub transport_layer_address_info: Option<TransportLayerAddressInfo>,
}

// CellsFailedToBeActivatedList
#[derive(Clone)]
pub struct CellsFailedToBeActivatedList(pub Vec<CellsFailedToBeActivatedListItem>);

// GnbCuTnlAssociationSetupList
#[derive(Clone)]
pub struct GnbCuTnlAssociationSetupList(pub Vec<GnbCuTnlAssociationSetupItem>);

// GnbCuTnlAssociationFailedToSetupList
#[derive(Clone)]
pub struct GnbCuTnlAssociationFailedToSetupList(pub Vec<GnbCuTnlAssociationFailedToSetupItem>);

// GnbCuConfigurationUpdateFailure
#[derive(Clone)]
pub struct GnbCuConfigurationUpdateFailure {
    pub transaction_id: TransactionId,
    pub cause: Cause,
    pub time_to_wait: Option<TimeToWait>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// GnbDuResourceCoordinationRequest
#[derive(Clone)]
pub struct GnbDuResourceCoordinationRequest {
    pub transaction_id: TransactionId,
    pub request_type: RequestType,
    pub eutra_nr_cell_resource_coordination_req_container:
        EutraNrCellResourceCoordinationReqContainer,
    pub ignore_resource_coordination_container: Option<IgnoreResourceCoordinationContainer>,
}

// GnbDuResourceCoordinationResponse
#[derive(Clone)]
pub struct GnbDuResourceCoordinationResponse {
    pub transaction_id: TransactionId,
    pub eutra_nr_cell_resource_coordination_req_ack_container:
        EutraNrCellResourceCoordinationReqAckContainer,
}

// UeContextSetupRequest
#[derive(Clone)]
pub struct UeContextSetupRequest {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: Option<GnbDuUeF1apId>,
    pub sp_cell_id: Nrcgi,
    pub serv_cell_index: ServCellIndex,
    pub sp_cell_ul_configured: Option<CellUlConfigured>,
    pub c_uto_durrc_information: CUtoDurrcInformation,
    pub candidate_sp_cell_list: Option<CandidateSpCellList>,
    pub drx_cycle: Option<DrxCycle>,
    pub resource_coordination_transfer_container: Option<ResourceCoordinationTransferContainer>,
    pub s_cell_to_be_setup_list: Option<SCellToBeSetupList>,
    pub sr_bs_to_be_setup_list: Option<SrBsToBeSetupList>,
    pub dr_bs_to_be_setup_list: Option<DrBsToBeSetupList>,
    pub inactivity_monitoring_request: Option<InactivityMonitoringRequest>,
    pub rat_frequency_priority_information: Option<RatFrequencyPriorityInformation>,
    pub rrc_container: Option<RrcContainer>,
    pub masked_imeisv: Option<MaskedImeisv>,
    pub serving_plmn: Option<PlmnIdentity>,
    pub gnb_du_ue_ambr_ul: Option<BitRate>,
    pub rrc_delivery_status_request: Option<RrcDeliveryStatusRequest>,
    pub resource_coordination_transfer_information: Option<ResourceCoordinationTransferInformation>,
    pub serving_cell_mo: Option<ServingCellMo>,
    pub new_gnb_cu_ue_f1ap_id: Option<GnbDuUeF1apId>,
    pub ranueid: Option<Ranueid>,
    pub trace_activation: Option<TraceActivation>,
    pub additional_rrm_priority_index: Option<AdditionalRrmPriorityIndex>,
    pub bh_channels_to_be_setup_list: Option<BhChannelsToBeSetupList>,
    pub configured_bap_address: Option<BapAddress>,
    pub nrv2x_services_authorized: Option<Nrv2xServicesAuthorized>,
    pub ltev2x_services_authorized: Option<Ltev2xServicesAuthorized>,
    pub nrue_sidelink_aggregate_maximum_bitrate: Option<NrueSidelinkAggregateMaximumBitrate>,
    pub lteue_sidelink_aggregate_maximum_bitrate: Option<LteueSidelinkAggregateMaximumBitrate>,
    pub pc5_link_ambr: Option<BitRate>,
    pub sldr_bs_to_be_setup_list: Option<SldrBsToBeSetupList>,
    pub conditional_inter_du_mobility_information: Option<ConditionalInterDuMobilityInformation>,
    pub management_based_mdt_plmn_list: Option<MdtPlmnList>,
    pub serving_nid: Option<Nid>,
    pub f1c_transfer_path: Option<F1cTransferPath>,
}

// CandidateSpCellList
#[derive(Clone)]
pub struct CandidateSpCellList(pub Vec<CandidateSpCellItem>);

// SCellToBeSetupList
#[derive(Clone)]
pub struct SCellToBeSetupList(pub Vec<SCellToBeSetupItem>);

// SrBsToBeSetupList
#[derive(Clone)]
pub struct SrBsToBeSetupList(pub Vec<SrBsToBeSetupItem>);

// DrBsToBeSetupList
#[derive(Clone)]
pub struct DrBsToBeSetupList(pub Vec<DrBsToBeSetupItem>);

// BhChannelsToBeSetupList
#[derive(Clone)]
pub struct BhChannelsToBeSetupList(pub Vec<BhChannelsToBeSetupItem>);

// SldrBsToBeSetupList
#[derive(Clone)]
pub struct SldrBsToBeSetupList(pub Vec<SldrBsToBeSetupItem>);

// UeContextSetupResponse
#[derive(Clone)]
pub struct UeContextSetupResponse {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub d_uto_currc_information: DUtoCurrcInformation,
    pub c_rnti: Option<CRnti>,
    pub resource_coordination_transfer_container: Option<ResourceCoordinationTransferContainer>,
    pub full_configuration: Option<FullConfiguration>,
    pub dr_bs_setup_list: Option<DrBsSetupList>,
    pub sr_bs_failed_to_be_setup_list: Option<SrBsFailedToBeSetupList>,
    pub dr_bs_failed_to_be_setup_list: Option<DrBsFailedToBeSetupList>,
    pub s_cell_failedto_setup_list: Option<SCellFailedtoSetupList>,
    pub inactivity_monitoring_response: Option<InactivityMonitoringResponse>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
    pub sr_bs_setup_list: Option<SrBsSetupList>,
    pub bh_channels_setup_list: Option<BhChannelsSetupList>,
    pub bh_channels_failed_to_be_setup_list: Option<BhChannelsFailedToBeSetupList>,
    pub sldr_bs_setup_list: Option<SldrBsSetupList>,
    pub sldr_bs_failed_to_be_setup_list: Option<SldrBsFailedToBeSetupList>,
    pub requested_target_cell_global_id: Option<Nrcgi>,
}

// DrBsSetupList
#[derive(Clone)]
pub struct DrBsSetupList(pub Vec<DrBsSetupItem>);

// SrBsFailedToBeSetupList
#[derive(Clone)]
pub struct SrBsFailedToBeSetupList(pub Vec<SrBsFailedToBeSetupItem>);

// DrBsFailedToBeSetupList
#[derive(Clone)]
pub struct DrBsFailedToBeSetupList(pub Vec<DrBsFailedToBeSetupItem>);

// SCellFailedtoSetupList
#[derive(Clone)]
pub struct SCellFailedtoSetupList(pub Vec<SCellFailedtoSetupItem>);

// SrBsSetupList
#[derive(Clone)]
pub struct SrBsSetupList(pub Vec<SrBsSetupItem>);

// BhChannelsSetupList
#[derive(Clone)]
pub struct BhChannelsSetupList(pub Vec<BhChannelsSetupItem>);

// BhChannelsFailedToBeSetupList
#[derive(Clone)]
pub struct BhChannelsFailedToBeSetupList(pub Vec<BhChannelsFailedToBeSetupItem>);

// SldrBsSetupList
#[derive(Clone)]
pub struct SldrBsSetupList(pub Vec<SldrBsSetupItem>);

// SldrBsFailedToBeSetupList
#[derive(Clone)]
pub struct SldrBsFailedToBeSetupList(pub Vec<SldrBsFailedToBeSetupItem>);

// UeContextSetupFailure
#[derive(Clone)]
pub struct UeContextSetupFailure {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: Option<GnbDuUeF1apId>,
    pub cause: Cause,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
    pub potential_sp_cell_list: Option<PotentialSpCellList>,
    pub requested_target_cell_global_id: Option<Nrcgi>,
}

// PotentialSpCellList
#[derive(Clone)]
pub struct PotentialSpCellList(pub Vec<PotentialSpCellItem>);

// UeContextReleaseRequest
#[derive(Clone)]
pub struct UeContextReleaseRequest {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub cause: Cause,
    pub target_cells_to_cancel: Option<TargetCellList>,
}

// UeContextReleaseCommand
#[derive(Clone)]
pub struct UeContextReleaseCommand {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub cause: Cause,
    pub rrc_container: Option<RrcContainer>,
    pub srbid: Option<Srbid>,
    pub old_gnb_du_ue_f1ap_id: Option<GnbDuUeF1apId>,
    pub execute_duplication: Option<ExecuteDuplication>,
    pub rrc_delivery_status_request: Option<RrcDeliveryStatusRequest>,
    pub target_cells_to_cancel: Option<TargetCellList>,
}

// UeContextReleaseComplete
#[derive(Clone)]
pub struct UeContextReleaseComplete {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// UeContextModificationRequest
#[derive(Clone)]
pub struct UeContextModificationRequest {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub sp_cell_id: Option<Nrcgi>,
    pub serv_cell_index: Option<ServCellIndex>,
    pub sp_cell_ul_configured: Option<CellUlConfigured>,
    pub drx_cycle: Option<DrxCycle>,
    pub c_uto_durrc_information: Option<CUtoDurrcInformation>,
    pub transmission_action_indicator: Option<TransmissionActionIndicator>,
    pub resource_coordination_transfer_container: Option<ResourceCoordinationTransferContainer>,
    pub rrc_reconfiguration_complete_indicator: Option<RrcReconfigurationCompleteIndicator>,
    pub rrc_container: Option<RrcContainer>,
    pub s_cell_to_be_setup_mod_list: Option<SCellToBeSetupModList>,
    pub s_cell_to_be_removed_list: Option<SCellToBeRemovedList>,
    pub sr_bs_to_be_setup_mod_list: Option<SrBsToBeSetupModList>,
    pub dr_bs_to_be_setup_mod_list: Option<DrBsToBeSetupModList>,
    pub dr_bs_to_be_modified_list: Option<DrBsToBeModifiedList>,
    pub sr_bs_to_be_released_list: Option<SrBsToBeReleasedList>,
    pub dr_bs_to_be_released_list: Option<DrBsToBeReleasedList>,
    pub inactivity_monitoring_request: Option<InactivityMonitoringRequest>,
    pub rat_frequency_priority_information: Option<RatFrequencyPriorityInformation>,
    pub drx_configuration_indicator: Option<DrxConfigurationIndicator>,
    pub rlc_failure_indication: Option<RlcFailureIndication>,
    pub uplink_tx_direct_current_list_information: Option<UplinkTxDirectCurrentListInformation>,
    pub gnb_du_configuration_query: Option<GnbDuConfigurationQuery>,
    pub gnb_du_ue_ambr_ul: Option<BitRate>,
    pub execute_duplication: Option<ExecuteDuplication>,
    pub rrc_delivery_status_request: Option<RrcDeliveryStatusRequest>,
    pub resource_coordination_transfer_information: Option<ResourceCoordinationTransferInformation>,
    pub serving_cell_mo: Option<ServingCellMo>,
    pub needfor_gap: Option<NeedforGap>,
    pub full_configuration: Option<FullConfiguration>,
    pub additional_rrm_priority_index: Option<AdditionalRrmPriorityIndex>,
    pub lower_layer_presence_status_change: Option<LowerLayerPresenceStatusChange>,
    pub bh_channels_to_be_setup_mod_list: Option<BhChannelsToBeSetupModList>,
    pub bh_channels_to_be_modified_list: Option<BhChannelsToBeModifiedList>,
    pub bh_channels_to_be_released_list: Option<BhChannelsToBeReleasedList>,
    pub nrv2x_services_authorized: Option<Nrv2xServicesAuthorized>,
    pub ltev2x_services_authorized: Option<Ltev2xServicesAuthorized>,
    pub nrue_sidelink_aggregate_maximum_bitrate: Option<NrueSidelinkAggregateMaximumBitrate>,
    pub lteue_sidelink_aggregate_maximum_bitrate: Option<LteueSidelinkAggregateMaximumBitrate>,
    pub pc5_link_ambr: Option<BitRate>,
    pub sldr_bs_to_be_setup_mod_list: Option<SldrBsToBeSetupModList>,
    pub sldr_bs_to_be_modified_list: Option<SldrBsToBeModifiedList>,
    pub sldr_bs_to_be_released_list: Option<SldrBsToBeReleasedList>,
    pub conditional_intra_du_mobility_information: Option<ConditionalIntraDuMobilityInformation>,
    pub f1c_transfer_path: Option<F1cTransferPath>,
    pub scg_indicator: Option<ScgIndicator>,
}

// SCellToBeSetupModList
#[derive(Clone)]
pub struct SCellToBeSetupModList(pub Vec<SCellToBeSetupModItem>);

// SCellToBeRemovedList
#[derive(Clone)]
pub struct SCellToBeRemovedList(pub Vec<SCellToBeRemovedItem>);

// SrBsToBeSetupModList
#[derive(Clone)]
pub struct SrBsToBeSetupModList(pub Vec<SrBsToBeSetupModItem>);

// DrBsToBeSetupModList
#[derive(Clone)]
pub struct DrBsToBeSetupModList(pub Vec<DrBsToBeSetupModItem>);

// BhChannelsToBeSetupModList
#[derive(Clone)]
pub struct BhChannelsToBeSetupModList(pub Vec<BhChannelsToBeSetupModItem>);

// DrBsToBeModifiedList
#[derive(Clone)]
pub struct DrBsToBeModifiedList(pub Vec<DrBsToBeModifiedItem>);

// BhChannelsToBeModifiedList
#[derive(Clone)]
pub struct BhChannelsToBeModifiedList(pub Vec<BhChannelsToBeModifiedItem>);

// SrBsToBeReleasedList
#[derive(Clone)]
pub struct SrBsToBeReleasedList(pub Vec<SrBsToBeReleasedItem>);

// DrBsToBeReleasedList
#[derive(Clone)]
pub struct DrBsToBeReleasedList(pub Vec<DrBsToBeReleasedItem>);

// BhChannelsToBeReleasedList
#[derive(Clone)]
pub struct BhChannelsToBeReleasedList(pub Vec<BhChannelsToBeReleasedItem>);

// SldrBsToBeSetupModList
#[derive(Clone)]
pub struct SldrBsToBeSetupModList(pub Vec<SldrBsToBeSetupModItem>);

// SldrBsToBeModifiedList
#[derive(Clone)]
pub struct SldrBsToBeModifiedList(pub Vec<SldrBsToBeModifiedItem>);

// SldrBsToBeReleasedList
#[derive(Clone)]
pub struct SldrBsToBeReleasedList(pub Vec<SldrBsToBeReleasedItem>);

// UeContextModificationResponse
#[derive(Clone)]
pub struct UeContextModificationResponse {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub resource_coordination_transfer_container: Option<ResourceCoordinationTransferContainer>,
    pub d_uto_currc_information: Option<DUtoCurrcInformation>,
    pub dr_bs_setup_mod_list: Option<DrBsSetupModList>,
    pub dr_bs_modified_list: Option<DrBsModifiedList>,
    pub sr_bs_failed_to_be_setup_mod_list: Option<SrBsFailedToBeSetupModList>,
    pub dr_bs_failed_to_be_setup_mod_list: Option<DrBsFailedToBeSetupModList>,
    pub s_cell_failedto_setup_mod_list: Option<SCellFailedtoSetupModList>,
    pub dr_bs_failed_to_be_modified_list: Option<DrBsFailedToBeModifiedList>,
    pub inactivity_monitoring_response: Option<InactivityMonitoringResponse>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
    pub c_rnti: Option<CRnti>,
    pub associated_s_cell_list: Option<AssociatedSCellList>,
    pub sr_bs_setup_mod_list: Option<SrBsSetupModList>,
    pub sr_bs_modified_list: Option<SrBsModifiedList>,
    pub full_configuration: Option<FullConfiguration>,
    pub bh_channels_setup_mod_list: Option<BhChannelsSetupModList>,
    pub bh_channels_modified_list: Option<BhChannelsModifiedList>,
    pub bh_channels_failed_to_be_setup_mod_list: Option<BhChannelsFailedToBeSetupModList>,
    pub bh_channels_failed_to_be_modified_list: Option<BhChannelsFailedToBeModifiedList>,
    pub sldr_bs_setup_mod_list: Option<SldrBsSetupModList>,
    pub sldr_bs_modified_list: Option<SldrBsModifiedList>,
    pub sldr_bs_failed_to_be_setup_mod_list: Option<SldrBsFailedToBeSetupModList>,
    pub sldr_bs_failed_to_be_modified_list: Option<SldrBsFailedToBeModifiedList>,
    pub requested_target_cell_global_id: Option<Nrcgi>,
}

// DrBsSetupModList
#[derive(Clone)]
pub struct DrBsSetupModList(pub Vec<DrBsSetupModItem>);

// DrBsModifiedList
#[derive(Clone)]
pub struct DrBsModifiedList(pub Vec<DrBsModifiedItem>);

// SrBsSetupModList
#[derive(Clone)]
pub struct SrBsSetupModList(pub Vec<SrBsSetupModItem>);

// SrBsModifiedList
#[derive(Clone)]
pub struct SrBsModifiedList(pub Vec<SrBsModifiedItem>);

// DrBsFailedToBeModifiedList
#[derive(Clone)]
pub struct DrBsFailedToBeModifiedList(pub Vec<DrBsFailedToBeModifiedItem>);

// SrBsFailedToBeSetupModList
#[derive(Clone)]
pub struct SrBsFailedToBeSetupModList(pub Vec<SrBsFailedToBeSetupModItem>);

// DrBsFailedToBeSetupModList
#[derive(Clone)]
pub struct DrBsFailedToBeSetupModList(pub Vec<DrBsFailedToBeSetupModItem>);

// SCellFailedtoSetupModList
#[derive(Clone)]
pub struct SCellFailedtoSetupModList(pub Vec<SCellFailedtoSetupModItem>);

// BhChannelsSetupModList
#[derive(Clone)]
pub struct BhChannelsSetupModList(pub Vec<BhChannelsSetupModItem>);

// BhChannelsModifiedList
#[derive(Clone)]
pub struct BhChannelsModifiedList(pub Vec<BhChannelsModifiedItem>);

// BhChannelsFailedToBeModifiedList
#[derive(Clone)]
pub struct BhChannelsFailedToBeModifiedList(pub Vec<BhChannelsFailedToBeModifiedItem>);

// BhChannelsFailedToBeSetupModList
#[derive(Clone)]
pub struct BhChannelsFailedToBeSetupModList(pub Vec<BhChannelsFailedToBeSetupModItem>);

// AssociatedSCellList
#[derive(Clone)]
pub struct AssociatedSCellList(pub Vec<AssociatedSCellItem>);

// SldrBsSetupModList
#[derive(Clone)]
pub struct SldrBsSetupModList(pub Vec<SldrBsSetupModItem>);

// SldrBsModifiedList
#[derive(Clone)]
pub struct SldrBsModifiedList(pub Vec<SldrBsModifiedItem>);

// SldrBsFailedToBeModifiedList
#[derive(Clone)]
pub struct SldrBsFailedToBeModifiedList(pub Vec<SldrBsFailedToBeModifiedItem>);

// SldrBsFailedToBeSetupModList
#[derive(Clone)]
pub struct SldrBsFailedToBeSetupModList(pub Vec<SldrBsFailedToBeSetupModItem>);

// UeContextModificationFailure
#[derive(Clone)]
pub struct UeContextModificationFailure {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub cause: Cause,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
    pub requested_target_cell_global_id: Option<Nrcgi>,
}

// UeContextModificationRequired
#[derive(Clone)]
pub struct UeContextModificationRequired {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub resource_coordination_transfer_container: Option<ResourceCoordinationTransferContainer>,
    pub d_uto_currc_information: Option<DUtoCurrcInformation>,
    pub dr_bs_required_to_be_modified_list: Option<DrBsRequiredToBeModifiedList>,
    pub sr_bs_required_to_be_released_list: Option<SrBsRequiredToBeReleasedList>,
    pub dr_bs_required_to_be_released_list: Option<DrBsRequiredToBeReleasedList>,
    pub cause: Cause,
    pub bh_channels_required_to_be_released_list: Option<BhChannelsRequiredToBeReleasedList>,
    pub sldr_bs_required_to_be_modified_list: Option<SldrBsRequiredToBeModifiedList>,
    pub sldr_bs_required_to_be_released_list: Option<SldrBsRequiredToBeReleasedList>,
    pub target_cells_to_cancel: Option<TargetCellList>,
}

// DrBsRequiredToBeModifiedList
#[derive(Clone)]
pub struct DrBsRequiredToBeModifiedList(pub Vec<DrBsRequiredToBeModifiedItem>);

// DrBsRequiredToBeReleasedList
#[derive(Clone)]
pub struct DrBsRequiredToBeReleasedList(pub Vec<DrBsRequiredToBeReleasedItem>);

// SrBsRequiredToBeReleasedList
#[derive(Clone)]
pub struct SrBsRequiredToBeReleasedList(pub Vec<SrBsRequiredToBeReleasedItem>);

// BhChannelsRequiredToBeReleasedList
#[derive(Clone)]
pub struct BhChannelsRequiredToBeReleasedList(pub Vec<BhChannelsRequiredToBeReleasedItem>);

// SldrBsRequiredToBeModifiedList
#[derive(Clone)]
pub struct SldrBsRequiredToBeModifiedList(pub Vec<SldrBsRequiredToBeModifiedItem>);

// SldrBsRequiredToBeReleasedList
#[derive(Clone)]
pub struct SldrBsRequiredToBeReleasedList(pub Vec<SldrBsRequiredToBeReleasedItem>);

// UeContextModificationConfirm
#[derive(Clone)]
pub struct UeContextModificationConfirm {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub resource_coordination_transfer_container: Option<ResourceCoordinationTransferContainer>,
    pub dr_bs_modified_conf_list: Option<DrBsModifiedConfList>,
    pub rrc_container: Option<RrcContainer>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
    pub execute_duplication: Option<ExecuteDuplication>,
    pub resource_coordination_transfer_information: Option<ResourceCoordinationTransferInformation>,
    pub sldr_bs_modified_conf_list: Option<SldrBsModifiedConfList>,
}

// DrBsModifiedConfList
#[derive(Clone)]
pub struct DrBsModifiedConfList(pub Vec<DrBsModifiedConfItem>);

// SldrBsModifiedConfList
#[derive(Clone)]
pub struct SldrBsModifiedConfList(pub Vec<SldrBsModifiedConfItem>);

// UeContextModificationRefuse
#[derive(Clone)]
pub struct UeContextModificationRefuse {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub cause: Cause,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// WriteReplaceWarningRequest
#[derive(Clone)]
pub struct WriteReplaceWarningRequest {
    pub transaction_id: TransactionId,
    pub pws_system_information: PwsSystemInformation,
    pub repetition_period: RepetitionPeriod,
    pub numberof_broadcast_request: NumberofBroadcastRequest,
    pub cells_to_be_broadcast_list: Option<CellsToBeBroadcastList>,
}

// CellsToBeBroadcastList
#[derive(Clone)]
pub struct CellsToBeBroadcastList(pub Vec<CellsToBeBroadcastListItem>);

// WriteReplaceWarningResponse
#[derive(Clone)]
pub struct WriteReplaceWarningResponse {
    pub transaction_id: TransactionId,
    pub cells_broadcast_completed_list: Option<CellsBroadcastCompletedList>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
    pub dedicated_si_delivery_needed_ue_list: Option<DedicatedSiDeliveryNeededUeList>,
}

// CellsBroadcastCompletedList
#[derive(Clone)]
pub struct CellsBroadcastCompletedList(pub Vec<CellsBroadcastCompletedListItem>);

// PwsCancelRequest
#[derive(Clone)]
pub struct PwsCancelRequest {
    pub transaction_id: TransactionId,
    pub numberof_broadcast_request: NumberofBroadcastRequest,
    pub broadcast_to_be_cancelled_list: Option<BroadcastToBeCancelledList>,
    pub cancel_all_warning_messages_indicator: Option<CancelAllWarningMessagesIndicator>,
    pub notification_information: Option<NotificationInformation>,
}

// BroadcastToBeCancelledList
#[derive(Clone)]
pub struct BroadcastToBeCancelledList(pub Vec<BroadcastToBeCancelledListItem>);

// PwsCancelResponse
#[derive(Clone)]
pub struct PwsCancelResponse {
    pub transaction_id: TransactionId,
    pub cells_broadcast_cancelled_list: Option<CellsBroadcastCancelledList>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// CellsBroadcastCancelledList
#[derive(Clone)]
pub struct CellsBroadcastCancelledList(pub Vec<CellsBroadcastCancelledListItem>);

// UeInactivityNotification
#[derive(Clone)]
pub struct UeInactivityNotification {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub drb_activity_list: DrbActivityList,
}

// DrbActivityList
#[derive(Clone)]
pub struct DrbActivityList(pub Vec<DrbActivityItem>);

// InitialUlrrcMessageTransfer
#[derive(Clone)]
pub struct InitialUlrrcMessageTransfer {
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub nrcgi: Nrcgi,
    pub c_rnti: CRnti,
    pub rrc_container: RrcContainer,
    pub d_uto_currc_container: Option<DUtoCurrcContainer>,
    pub sul_access_indication: Option<SulAccessIndication>,
    pub transaction_id: TransactionId,
    pub ranueid: Option<Ranueid>,
    pub rrc_container_rrc_setup_complete: Option<RrcContainerRrcSetupComplete>,
}

// DlrrcMessageTransfer
#[derive(Clone)]
pub struct DlrrcMessageTransfer {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub old_gnb_du_ue_f1ap_id: Option<GnbDuUeF1apId>,
    pub srbid: Srbid,
    pub execute_duplication: Option<ExecuteDuplication>,
    pub rrc_container: RrcContainer,
    pub rat_frequency_priority_information: Option<RatFrequencyPriorityInformation>,
    pub rrc_delivery_status_request: Option<RrcDeliveryStatusRequest>,
    pub ue_context_not_retrievable: Option<UeContextNotRetrievable>,
    pub redirected_rr_cmessage: Option<Vec<u8>>,
    pub plmn_assistance_info_for_net_shar: Option<PlmnIdentity>,
    pub new_gnb_cu_ue_f1ap_id: Option<GnbCuUeF1apId>,
    pub additional_rrm_priority_index: Option<AdditionalRrmPriorityIndex>,
}

// UlrrcMessageTransfer
#[derive(Clone)]
pub struct UlrrcMessageTransfer {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub srbid: Srbid,
    pub rrc_container: RrcContainer,
    pub selected_plmn_id: Option<PlmnIdentity>,
    pub new_gnb_du_ue_f1ap_id: Option<GnbDuUeF1apId>,
}
// PrivateMessage - omitted

// SystemInformationDeliveryCommand
#[derive(Clone)]
pub struct SystemInformationDeliveryCommand {
    pub transaction_id: TransactionId,
    pub nrcgi: Nrcgi,
    pub s_itype_list: SItypeList,
    pub confirmed_ueid: GnbDuUeF1apId,
}

// Paging
#[derive(Clone)]
pub struct Paging {
    pub ue_identity_index_value: UeIdentityIndexValue,
    pub paging_identity: PagingIdentity,
    pub paging_drx: Option<PagingDrx>,
    pub paging_priority: Option<PagingPriority>,
    pub paging_cell_list: PagingCellList,
    pub paging_origin: Option<PagingOrigin>,
}

// PagingCellList
#[derive(Clone)]
pub struct PagingCellList(pub Vec<PagingCellItem>);

// Notify
#[derive(Clone)]
pub struct Notify {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub drb_notify_list: DrbNotifyList,
}

// DrbNotifyList
#[derive(Clone)]
pub struct DrbNotifyList(pub Vec<DrbNotifyItem>);

// NetworkAccessRateReduction
#[derive(Clone)]
pub struct NetworkAccessRateReduction {
    pub transaction_id: TransactionId,
    pub uac_assistance_info: UacAssistanceInfo,
}

// PwsRestartIndication
#[derive(Clone)]
pub struct PwsRestartIndication {
    pub transaction_id: TransactionId,
    pub nr_cgi_list_for_restart_list: NrCgiListForRestartList,
}

// NrCgiListForRestartList
#[derive(Clone)]
pub struct NrCgiListForRestartList(pub Vec<NrCgiListForRestartListItem>);

// PwsFailureIndication
#[derive(Clone)]
pub struct PwsFailureIndication {
    pub transaction_id: TransactionId,
    pub pws_failed_nr_cgi_list: Option<PwsFailedNrCgiList>,
}

// PwsFailedNrCgiList
#[derive(Clone)]
pub struct PwsFailedNrCgiList(pub Vec<PwsFailedNrCgiListItem>);

// GnbDuStatusIndication
#[derive(Clone)]
pub struct GnbDuStatusIndication {
    pub transaction_id: TransactionId,
    pub gnb_du_overload_information: GnbDuOverloadInformation,
}

// RrcDeliveryReport
#[derive(Clone)]
pub struct RrcDeliveryReport {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub rrc_delivery_status: RrcDeliveryStatus,
    pub srbid: Srbid,
}

// F1RemovalRequest
#[derive(Clone)]
pub struct F1RemovalRequest {
    pub transaction_id: TransactionId,
}

// F1RemovalResponse
#[derive(Clone)]
pub struct F1RemovalResponse {
    pub transaction_id: TransactionId,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// F1RemovalFailure
#[derive(Clone)]
pub struct F1RemovalFailure {
    pub transaction_id: TransactionId,
    pub cause: Cause,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// TraceStart
#[derive(Clone)]
pub struct TraceStart {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub trace_activation: TraceActivation,
}

// DeactivateTrace
#[derive(Clone)]
pub struct DeactivateTrace {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub trace_id: TraceId,
}

// CellTrafficTrace
#[derive(Clone)]
pub struct CellTrafficTrace {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub trace_id: TraceId,
    pub trace_collection_entity_ip_address: TransportLayerAddress,
    pub privacy_indicator: Option<PrivacyIndicator>,
    pub trace_collection_entity_uri: Option<UriAddress>,
}

// DucuRadioInformationTransfer
#[derive(Clone)]
pub struct DucuRadioInformationTransfer {
    pub transaction_id: TransactionId,
    pub ducu_radio_information_type: DucuRadioInformationType,
}

// CuduRadioInformationTransfer
#[derive(Clone)]
pub struct CuduRadioInformationTransfer {
    pub transaction_id: TransactionId,
    pub cudu_radio_information_type: CuduRadioInformationType,
}

// BapMappingConfiguration
#[derive(Clone)]
pub struct BapMappingConfiguration {
    pub transaction_id: TransactionId,
    pub bh_routing_information_added_list: Option<BhRoutingInformationAddedList>,
    pub bh_routing_information_removed_list: Option<BhRoutingInformationRemovedList>,
    pub traffic_mapping_information: Option<TrafficMappingInfo>,
}

// BhRoutingInformationAddedList
#[derive(Clone)]
pub struct BhRoutingInformationAddedList(pub Vec<BhRoutingInformationAddedListItem>);

// BhRoutingInformationRemovedList
#[derive(Clone)]
pub struct BhRoutingInformationRemovedList(pub Vec<BhRoutingInformationRemovedListItem>);

// BapMappingConfigurationAcknowledge
#[derive(Clone)]
pub struct BapMappingConfigurationAcknowledge {
    pub transaction_id: TransactionId,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// BapMappingConfigurationFailure
#[derive(Clone)]
pub struct BapMappingConfigurationFailure {
    pub transaction_id: TransactionId,
    pub cause: Cause,
    pub time_to_wait: Option<TimeToWait>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// GnbDuResourceConfiguration
#[derive(Clone)]
pub struct GnbDuResourceConfiguration {
    pub transaction_id: TransactionId,
    pub activated_cells_to_be_updated_list: Option<ActivatedCellsToBeUpdatedList>,
    pub child_nodes_list: Option<ChildNodesList>,
}

// GnbDuResourceConfigurationAcknowledge
#[derive(Clone)]
pub struct GnbDuResourceConfigurationAcknowledge {
    pub transaction_id: TransactionId,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// GnbDuResourceConfigurationFailure
#[derive(Clone)]
pub struct GnbDuResourceConfigurationFailure {
    pub transaction_id: TransactionId,
    pub cause: Cause,
    pub time_to_wait: Option<TimeToWait>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// IabtnlAddressRequest
#[derive(Clone)]
pub struct IabtnlAddressRequest {
    pub transaction_id: TransactionId,
    pub ia_bv_4_addresses_requested: Option<IaBv4AddressesRequested>,
    pub iabi_pv_6_request_type: Option<IabiPv6RequestType>,
    pub iab_tnl_addresses_to_remove_list: Option<IabTnlAddressesToRemoveList>,
}

// IabTnlAddressesToRemoveList
#[derive(Clone)]
pub struct IabTnlAddressesToRemoveList(pub Vec<IabTnlAddressesToRemoveItem>);

// IabtnlAddressResponse
#[derive(Clone)]
pub struct IabtnlAddressResponse {
    pub transaction_id: TransactionId,
    pub iab_allocated_tnl_address_list: IabAllocatedTnlAddressList,
}

// IabAllocatedTnlAddressList
#[derive(Clone)]
pub struct IabAllocatedTnlAddressList(pub Vec<IabAllocatedTnlAddressListItem>);

// IabtnlAddressFailure
#[derive(Clone)]
pub struct IabtnlAddressFailure {
    pub transaction_id: TransactionId,
    pub cause: Cause,
    pub time_to_wait: Option<TimeToWait>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// IabupConfigurationUpdateRequest
#[derive(Clone)]
pub struct IabupConfigurationUpdateRequest {
    pub transaction_id: TransactionId,
    pub ul_up_tnl_information_to_update_list: Option<UlUpTnlInformationToUpdateList>,
    pub ul_up_tnl_address_to_update_list: Option<UlUpTnlAddressToUpdateList>,
}

// UlUpTnlInformationToUpdateList
#[derive(Clone)]
pub struct UlUpTnlInformationToUpdateList(pub Vec<UlUpTnlInformationToUpdateListItem>);

// UlUpTnlAddressToUpdateList
#[derive(Clone)]
pub struct UlUpTnlAddressToUpdateList(pub Vec<UlUpTnlAddressToUpdateListItem>);

// IabupConfigurationUpdateResponse
#[derive(Clone)]
pub struct IabupConfigurationUpdateResponse {
    pub transaction_id: TransactionId,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
    pub dl_up_tnl_address_to_update_list: Option<DlUpTnlAddressToUpdateList>,
}

// DlUpTnlAddressToUpdateList
#[derive(Clone)]
pub struct DlUpTnlAddressToUpdateList(pub Vec<DlUpTnlAddressToUpdateListItem>);

// IabupConfigurationUpdateFailure
#[derive(Clone)]
pub struct IabupConfigurationUpdateFailure {
    pub transaction_id: TransactionId,
    pub cause: Cause,
    pub time_to_wait: Option<TimeToWait>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// ResourceStatusRequest
#[derive(Clone)]
pub struct ResourceStatusRequest {
    pub transaction_id: TransactionId,
    pub gnb_cu_measurement_id: GnbCuMeasurementId,
    pub gnb_du_measurement_id: Option<GnbDuMeasurementId>,
    pub registration_request: RegistrationRequest,
    pub report_characteristics: Option<ReportCharacteristics>,
    pub cell_to_report_list: Option<CellToReportList>,
    pub reporting_periodicity: Option<ReportingPeriodicity>,
}

// ResourceStatusResponse
#[derive(Clone)]
pub struct ResourceStatusResponse {
    pub transaction_id: TransactionId,
    pub gnb_cu_measurement_id: GnbCuMeasurementId,
    pub gnb_du_measurement_id: GnbDuMeasurementId,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// ResourceStatusFailure
#[derive(Clone)]
pub struct ResourceStatusFailure {
    pub transaction_id: TransactionId,
    pub gnb_cu_measurement_id: GnbCuMeasurementId,
    pub gnb_du_measurement_id: GnbDuMeasurementId,
    pub cause: Cause,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// ResourceStatusUpdate
#[derive(Clone)]
pub struct ResourceStatusUpdate {
    pub transaction_id: TransactionId,
    pub gnb_cu_measurement_id: GnbCuMeasurementId,
    pub gnb_du_measurement_id: GnbDuMeasurementId,
    pub hardware_load_indicator: Option<HardwareLoadIndicator>,
    pub tnl_capacity_indicator: Option<TnlCapacityIndicator>,
    pub cell_measurement_result_list: Option<CellMeasurementResultList>,
}

// AccessAndMobilityIndication
#[derive(Clone)]
pub struct AccessAndMobilityIndication {
    pub transaction_id: TransactionId,
    pub rach_report_information_list: Option<RachReportInformationList>,
    pub rlf_report_information_list: Option<RlfReportInformationList>,
}

// ReferenceTimeInformationReportingControl
#[derive(Clone)]
pub struct ReferenceTimeInformationReportingControl {
    pub transaction_id: TransactionId,
    pub reporting_request_type: ReportingRequestType,
}

// ReferenceTimeInformationReport
#[derive(Clone)]
pub struct ReferenceTimeInformationReport {
    pub transaction_id: TransactionId,
    pub time_reference_information: TimeReferenceInformation,
}

// AccessSuccess
#[derive(Clone)]
pub struct AccessSuccess {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub nrcgi: Nrcgi,
}

// PositioningAssistanceInformationControl
#[derive(Clone)]
pub struct PositioningAssistanceInformationControl {
    pub transaction_id: TransactionId,
    pub pos_assistance_information: Option<PosAssistanceInformation>,
    pub pos_broadcast: Option<PosBroadcast>,
    pub positioning_broadcast_cells: Option<PositioningBroadcastCells>,
    pub routing_id: Option<RoutingId>,
}

// PositioningAssistanceInformationFeedback
#[derive(Clone)]
pub struct PositioningAssistanceInformationFeedback {
    pub transaction_id: TransactionId,
    pub pos_assistance_information_failure_list: Option<PosAssistanceInformationFailureList>,
    pub positioning_broadcast_cells: Option<PositioningBroadcastCells>,
    pub routing_id: Option<RoutingId>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// PositioningMeasurementRequest
#[derive(Clone)]
pub struct PositioningMeasurementRequest {
    pub transaction_id: TransactionId,
    pub lmf_measurement_id: LmfMeasurementId,
    pub ran_measurement_id: RanMeasurementId,
    pub trp_measurement_request_list: TrpMeasurementRequestList,
    pub pos_report_characteristics: PosReportCharacteristics,
    pub pos_measurement_periodicity: Option<MeasurementPeriodicity>,
    pub pos_measurement_quantities: PosMeasurementQuantities,
    pub sfn_initialisation_time: Option<RelativeTime1900>,
    pub srs_configuration: Option<SrsConfiguration>,
    pub measurement_beam_info_request: Option<MeasurementBeamInfoRequest>,
    pub system_frame_number: Option<SystemFrameNumber>,
    pub slot_number: Option<SlotNumber>,
}

// PositioningMeasurementResponse
#[derive(Clone)]
pub struct PositioningMeasurementResponse {
    pub transaction_id: TransactionId,
    pub lmf_measurement_id: LmfMeasurementId,
    pub ran_measurement_id: RanMeasurementId,
    pub pos_measurement_result_list: Option<PosMeasurementResultList>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// PositioningMeasurementFailure
#[derive(Clone)]
pub struct PositioningMeasurementFailure {
    pub transaction_id: TransactionId,
    pub lmf_measurement_id: LmfMeasurementId,
    pub ran_measurement_id: RanMeasurementId,
    pub cause: Cause,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// PositioningMeasurementReport
#[derive(Clone)]
pub struct PositioningMeasurementReport {
    pub transaction_id: TransactionId,
    pub lmf_measurement_id: LmfMeasurementId,
    pub ran_measurement_id: RanMeasurementId,
    pub pos_measurement_result_list: PosMeasurementResultList,
}

// PositioningMeasurementAbort
#[derive(Clone)]
pub struct PositioningMeasurementAbort {
    pub transaction_id: TransactionId,
    pub lmf_measurement_id: LmfMeasurementId,
    pub ran_measurement_id: RanMeasurementId,
}

// PositioningMeasurementFailureIndication
#[derive(Clone)]
pub struct PositioningMeasurementFailureIndication {
    pub transaction_id: TransactionId,
    pub lmf_measurement_id: LmfMeasurementId,
    pub ran_measurement_id: RanMeasurementId,
    pub cause: Cause,
}

// PositioningMeasurementUpdate
#[derive(Clone)]
pub struct PositioningMeasurementUpdate {
    pub transaction_id: TransactionId,
    pub lmf_measurement_id: LmfMeasurementId,
    pub ran_measurement_id: RanMeasurementId,
    pub srs_configuration: Option<SrsConfiguration>,
}

// TrpInformationRequest
#[derive(Clone)]
pub struct TrpInformationRequest {
    pub transaction_id: TransactionId,
    pub trp_list: Option<TrpList>,
    pub trp_information_type_list_trp_req: TrpInformationTypeListTrpReq,
}

// TrpInformationTypeListTrpReq
#[derive(Clone)]
pub struct TrpInformationTypeListTrpReq(pub Vec<TrpInformationTypeItemTrpReq>);

// TrpInformationResponse
#[derive(Clone)]
pub struct TrpInformationResponse {
    pub transaction_id: TransactionId,
    pub trp_information_list_trp_resp: TrpInformationListTrpResp,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// TrpInformationListTrpResp
#[derive(Clone)]
pub struct TrpInformationListTrpResp(pub Vec<TrpInformationItemTrpResp>);

// TrpInformationFailure
#[derive(Clone)]
pub struct TrpInformationFailure {
    pub transaction_id: TransactionId,
    pub cause: Cause,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// PositioningInformationRequest
#[derive(Clone)]
pub struct PositioningInformationRequest {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub requested_srs_transmission_characteristics: Option<RequestedSrsTransmissionCharacteristics>,
}

// PositioningInformationResponse
#[derive(Clone)]
pub struct PositioningInformationResponse {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub srs_configuration: Option<SrsConfiguration>,
    pub sfn_initialisation_time: Option<RelativeTime1900>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// PositioningInformationFailure
#[derive(Clone)]
pub struct PositioningInformationFailure {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub cause: Cause,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// PositioningActivationRequest
#[derive(Clone)]
pub struct PositioningActivationRequest {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub srs_type: SrsType,
    pub activation_time: Option<RelativeTime1900>,
}

// SrsType
#[derive(Clone)]
pub enum SrsType {
    SemipersistentSrs(SemipersistentSrs),
    AperiodicSrs(AperiodicSrs),
}

// SemipersistentSrs
#[derive(Clone)]
pub struct SemipersistentSrs {
    pub srs_resource_set_id: SrsResourceSetId,
    pub srs_spatial_relation: Option<SpatialRelationInfo>,
}

// AperiodicSrs
#[derive(Clone)]
pub struct AperiodicSrs {
    pub aperiodic: Aperiodic,
    pub srs_resource_trigger: Option<SrsResourceTrigger>,
}

// PositioningActivationResponse
#[derive(Clone)]
pub struct PositioningActivationResponse {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub system_frame_number: Option<SystemFrameNumber>,
    pub slot_number: Option<SlotNumber>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// PositioningActivationFailure
#[derive(Clone)]
pub struct PositioningActivationFailure {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub cause: Cause,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// PositioningDeactivation
#[derive(Clone)]
pub struct PositioningDeactivation {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub abort_transmission: AbortTransmission,
}

// PositioningInformationUpdate
#[derive(Clone)]
pub struct PositioningInformationUpdate {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub srs_configuration: Option<SrsConfiguration>,
    pub sfn_initialisation_time: Option<RelativeTime1900>,
}

// ECidMeasurementInitiationRequest
#[derive(Clone)]
pub struct ECidMeasurementInitiationRequest {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub lmf_ue_measurement_id: LmfUeMeasurementId,
    pub ran_ue_measurement_id: RanUeMeasurementId,
    pub e_cid_report_characteristics: ECidReportCharacteristics,
    pub e_cid_measurement_periodicity: Option<MeasurementPeriodicity>,
    pub e_cid_measurement_quantities: ECidMeasurementQuantities,
}

// ECidMeasurementInitiationResponse
#[derive(Clone)]
pub struct ECidMeasurementInitiationResponse {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub lmf_ue_measurement_id: LmfUeMeasurementId,
    pub ran_ue_measurement_id: RanUeMeasurementId,
    pub e_cid_measurement_result: Option<ECidMeasurementResult>,
    pub cell_portion_id: Option<CellPortionId>,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// ECidMeasurementInitiationFailure
#[derive(Clone)]
pub struct ECidMeasurementInitiationFailure {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub lmf_ue_measurement_id: LmfUeMeasurementId,
    pub ran_ue_measurement_id: RanUeMeasurementId,
    pub cause: Cause,
    pub criticality_diagnostics: Option<CriticalityDiagnostics>,
}

// ECidMeasurementFailureIndication
#[derive(Clone)]
pub struct ECidMeasurementFailureIndication {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub lmf_ue_measurement_id: LmfUeMeasurementId,
    pub ran_ue_measurement_id: RanUeMeasurementId,
    pub cause: Cause,
}

// ECidMeasurementReport
#[derive(Clone)]
pub struct ECidMeasurementReport {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub lmf_ue_measurement_id: LmfUeMeasurementId,
    pub ran_ue_measurement_id: RanUeMeasurementId,
    pub e_cid_measurement_result: ECidMeasurementResult,
    pub cell_portion_id: Option<CellPortionId>,
}

// ECidMeasurementTerminationCommand
#[derive(Clone)]
pub struct ECidMeasurementTerminationCommand {
    pub gnb_cu_ue_f1ap_id: GnbCuUeF1apId,
    pub gnb_du_ue_f1ap_id: GnbDuUeF1apId,
    pub lmf_ue_measurement_id: LmfUeMeasurementId,
    pub ran_ue_measurement_id: RanUeMeasurementId,
}

// Aperiodic
#[derive(Clone, Copy)]
pub enum Aperiodic {
    True,
}
