[package]
name = "ngap"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
#asn1-codecs = { path = "../../hampi/codecs" }
asn1-codecs = { git = "https://github.com/nplrkn/hampi", branch="all-fixes" }
hex = "0.4.3"
num_enum = "0.5.7"
bitvec = { version = "0.22" }
async-trait = "0.1.51"
net = { path = "../net" }
slog = "2.7.0"
anyhow = "1.0.52"


