[package]
name = "xxap-transaction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asn1-codecs = { path = "../../hampi/codecs" }
async-trait = "0.1.51"
slog = "2.7.0"
anyhow = "1.0.52"

