openapi: "3.0.0"
info:
  version: 1.0.0
  title: AlsoRAN Node Control API
  license:
    name: MIT
servers:
  - url: http://localhost/v1
paths:
  /worker:
    post:
      summary: Refresh worker request
      operationId: refreshWorker
      requestBody:
        description: Worker information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshWorkerReq'
      responses:
        '200':
          description: Refresh worker response
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/RefreshWorkerRsp"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      callbacks:
        interfaceManagement:
          /trigger/{tnlaId}:
            post: 
              summary: A worker is instructed to trigger an interface management procedure on the given TNLA.
              operationId: triggerInterfaceManagement
              parameters: 
                - in: path
                  name: tnlaId
                  required: true
                  schema:
                    type: integer
                    minimum: 1
              requestBody: 
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/InterfaceManagementReq'
              responses:
                '204':
                  description: Interface management response
                default:
                  description: Unexpected error
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Error"
components:
  schemas:
    RefreshWorkerReq:
      type: object
      required:
        - workerUniqueId
        - f1Address
        - connectedAmfs
        - connectedDus
      properties:
        workerUniqueId:
          type: string
          format: uuid
        f1Address:
          $ref: '#/components/schemas/TransportAddress'
        connectedAmfs:
          type: array
          items: 
            type: string
        connectedDus:
          type: array
          items: 
            type: string
    RefreshWorkerRsp:
      type: object
      required: 
        - amfAddresses
      properties:
        amfAddresses:
          type: array
          items: 
            $ref: '#/components/schemas/TransportAddress'
          minItems: 1
          uniqueItems: true
    InterfaceManagementReq:
      type: object
      required: 
        - procedure
      properties:
        procedure: 
          type: string
          enum: 
            - ngSetup
            - ranConfigurationUpdate
    TransportAddress:
      type: object
      required: 
        - host
      properties:
        host:
          type: string
          format: hostname
        port: 
          type: integer
          minimum: 1
          maximum: 65535
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string