name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install lld
      run: |
        sudo apt-get update
        sudo apt-get install lld
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: RUST_LOG=info RUST_TEST_THREADS=1 cargo test --verbose -- --nocapture
