openapi: 3.0.0
info:
  license:
    name: MIT
  title: AlsoRAN Coordination API
  version: 1.0.0
servers:
- url: http://localhost/v1
paths:
  /refreshWorker:
    post:
      operationId: refreshWorker
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshWorker'
        required: true
      responses:
        "204":
          description: Successful refresh
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Failed refresh
      summary: Updates coordinator with information about a worker instance
components:
  schemas:
    RefreshWorker:
      example:
        workerId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        revisionNumber: 0
        connectionState:
          ngUp: ""
          e1Up: ""
          f1Up: ""
        workerInfo:
          e1Address: e1Address
          f1Address: f1Address
          connectionApiUrl: http://example.com/aeiou
      properties:
        workerId:
          format: uuid
          type: string
        revisionNumber:
          type: integer
        workerInfo:
          $ref: '#/components/schemas/WorkerInfo'
        connectionState:
          $ref: '#/components/schemas/ConnectionState'
      required:
      - connectionState
      - revisionNumber
      - workerId
      - workerInfo
      type: object
    ConnectionState:
      example:
        ngUp: ""
        e1Up: ""
        f1Up: ""
      properties:
        ngUp:
          type: bool
        e1Up:
          type: bool
        f1Up:
          type: bool
      required:
      - e1Up
      - f1Up
      - ngUp
      type: object
    WorkerInfo:
      example:
        e1Address: e1Address
        f1Address: f1Address
        connectionApiUrl: http://example.com/aeiou
      properties:
        connectionApiUrl:
          format: url
          type: string
        f1Address:
          type: string
        e1Address:
          type: string
      required:
      - connectionApiUrl
      - e1Address
      - f1Address
      type: object
    IpAddress:
      type: string
    Error:
      type: string

