openapi: 3.0.0
info:
  license:
    name: MIT
  title: AlsoRAN Coordination API
  version: 1.0.0
servers:
- url: http://localhost/v1
paths:
  /refreshWorker:
    post:
      operationId: refreshWorker
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkerInfo'
        description: Worker Information
        required: true
      responses:
        "204":
          description: Successful refresh
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Failed refresh
      summary: Updates coordinator with information about a worker instance
components:
  schemas:
    WorkerInfo:
      example:
        workerUniqueId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        e1Address: e1Address
        connectedAmfs:
        - connectedAmfs
        - connectedAmfs
        f1Address: f1Address
        connectionApiUrl: http://example.com/aeiou
        connectedDus:
        - connectedDus
        - connectedDus
        connectedUps:
        - connectedUps
        - connectedUps
      properties:
        workerUniqueId:
          format: uuid
          type: string
        connectionApiUrl:
          format: url
          type: string
        f1Address:
          type: string
        e1Address:
          type: string
        connectedAmfs:
          items:
            type: string
          type: array
        connectedDus:
          items:
            type: string
          type: array
        connectedUps:
          items:
            type: string
          type: array
      required:
      - connectedAmfs
      - connectedDus
      - connectedUps
      - connectionApiUrl
      - e1Address
      - f1Address
      - workerUniqueId
      type: object
    IpAddress:
      type: string
    Error:
      type: string

